import { Html, Head, Main, NextScript } from 'next/document';
import { StyledComponentsRegistry } from '@app/components';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Document = () => {
  return (
    <Html lang="pt-br">
      <Head />
      <body>
        <StyledComponentsRegistry>
          <Main />
        </StyledComponentsRegistry>
        <NextScript />
      </body>
    </Html>
  );
};

export default Document;
